version: '3'

services:
  backend:
    build: ./services/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/backend/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./dev.env

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend/:/usr/src/app/

  nginx:
    image: staticfloat/nginx-certbot
    environment:
      CERTBOT_EMAIL: "masoud.javeri@housee.ai"
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: dev.housee.ai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
volumes:
    letsencrypt:
